FROM selenium/standalone-all-browsers

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 10000

CMD ["pytest", "-v", "groceries/tests/selenium_tests"]